version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whm_fe
    restart: always
    ports:
      - 3011:3000
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - sevira-network
networks:
  sevira-network:
    external: true
