import { ThemeProvider, styled } from '@mui/material'
import { Inter } from 'next/font/google'
import theme from '../styles/theme'
import './globals.css'
import { grey } from '@mui/material/colors';
const inter = Inter({ subsets: ['latin'] })
import StoreProvider from '@/store/StoreProvider'
import React from 'react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}




export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body
        className={inter.className}
        style={{
          margin: 0,
          padding: 0,
          backgroundColor: grey[200],
        }}
        >
          {children}
        </body>
      </ThemeProvider>
    </html>
    </StoreProvider>
  )
}
